### PR TITLE
Fixed a defect in callback parameter passing mechanism for __amd64__ …

### PR DESCRIPTION
**Pull request by sudheerhebbale**
Hello,

The scenario is that of a callback from c to lua (via a function pointer).

The compile_callback, function compiles the interface of a lua function and generates a function pointer which can be invoked at run time.

In the case of a function prototype with more than 6 integer type parameters, the calling convention of __amd64__ requires that all subsequent integer type parameters starting the 7th parameter be placed on the stack with an alignment of 8 bytes. However, the get_int function is trying to fit the parameters under 8 bytes (say int) within (i.e.) unaligned.

This causes parameter values being incorrectly passed on the stack to the called function.

Please review the change made to fix the problem and promote if suitable.

Regards,
Sudheer

### CODE REVIEW

**Comment by v1993** [comment]
AFAIK this repository is no longer maintained.

**Comment by sudheerhebbale** [comment]
> AFAIK this repository is no longer maintained.

Thanks for the information, it is unfortunate. The library otherwise is quite useful

**Comment by colesbury** [comment]
Thank you for the fix @sudheerhebbale. I will review and test it on Monday.

We are not actively using or maintaining this project anymore, but I'm happy to review small bug fixes.

**Review by colesbury — APPROVED** [review]

**Comment by sudheerhebbale** [comment]
Thanks

**Pull request merged**
